#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & polybar & xsetroot -cursor_name left_ptr &

# wallpaper
feh feh --bg-fill ~/.wallpapers/184933.jpg & 

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

normal="#1c4966"
accent="#45b6fe"

bspc config focused_border_color $accent
bspc config normal_border_color $normal
